### ISSUE TITLE
Styling the Analytics Graphs

### ISSUE THREAD

**Issue by chathura-de-silva** [chathura-de-silva/E-Commerce-Platform#50]

**Comment by luckylukezzz** [comment]
![image](https://github.com/chathura-de-silva/E-Commerce-Platform/assets/50476499/69c6e6bd-d7f1-4577-9466-5b11f5e4eb4a)
 changed styles a bit

**Comment by chathura-de-silva** [comment]
I did a revamp. Matching the colors. Still have to add some padding between inner elements of each block and also have to try to do some tweaks to the graphs look itself.

**Comment by chathura-de-silva** [comment]
@luckylukezzz  Can you add some padding to the elements.
